CREATE TABLE `project` (
  `project_no` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '프로젝트 번호',
  `organize_no` int(10) unsigned NOT NULL COMMENT '조직 번호',
  `bill_member_no` bigint(20) unsigned NOT NULL COMMENT '프로젝트 생성자 계정 번호',
  `member_no` bigint(20) unsigned NOT NULL COMMENT '프로젝트 생성자 회원 번호',
  `bill_member_type` smallint(5) unsigned NOT NULL COMMENT '빌멤버 타입',
  `project_name` json NOT NULL COMMENT '프로젝트 이름',
  `keyword` varchar(302) NOT NULL,
  `project_subtitle` json DEFAULT NULL COMMENT '프로젝트 서브타이틀',
  `project_desc` json DEFAULT NULL COMMENT '프로젝트 설명',
  `rep_image` json DEFAULT NULL COMMENT '대표이미지',
  `main_image` json DEFAULT NULL COMMENT '새대표이미지',
  `rep_logo_image` json DEFAULT NULL COMMENT '대표 로고 이미지',
  `rep_banner_image` json DEFAULT NULL COMMENT '대표 배너 이미지',
  `except_countries` varchar(50) DEFAULT NULL COMMENT '서비스 제외국가',
  `support_langs` json NOT NULL COMMENT '지원 언어',
  `images` json DEFAULT NULL COMMENT '이미지영역',
  `contents_grade` varchar(10) DEFAULT NULL COMMENT '컨텐츠 등급',
  `video_url` json DEFAULT NULL COMMENT '동영상 URL',
  `pre_reg_url` varchar(200) DEFAULT NULL COMMENT '사전예약 url',
  `app_no` int(10) unsigned DEFAULT NULL COMMENT '매핑된 app_no',
  `open_type` varchar(10) DEFAULT 'CLOSED' COMMENT 'SOON, CBT, OBT',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0 : 삭제, 1 : 정상, 2: 정상 && 포털 공개',
  `use_bora_detail` varchar(1) DEFAULT '1' COMMENT '상세페이지사용여부(0:미사용,1:사용)',
  `category_conf_no` int(10) unsigned DEFAULT NULL COMMENT '프로젝트 카테고리',
  `category` varchar(50) NOT NULL COMMENT 'category code',
  `app_env` varchar(10) DEFAULT NULL,
  `service_url` json DEFAULT NULL COMMENT '서비스페이지URL',
  `view_count` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '방문 기록 카운트',
  `share_count` json DEFAULT NULL COMMENT '공유 기록 카운트',
  `release_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `reg_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  `upd_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`project_no`),
  UNIQUE KEY `idx_project_app_no` (`app_no`),
)

CREATE TABLE `project_cs` (
  `project_cs_no` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '조직 번호',
  `project_no` bigint(20) unsigned NOT NULL COMMENT '조직 생성자 계정 번호',
  `organize_no` bigint(20) unsigned NOT NULL COMMENT '조직 생성자 계정 번호',
  `use_bora_cs` varchar(1) DEFAULT '1' COMMENT '보라CS사용여부(0:미사용,1:사용,2:이메일받기)',
  `phone` varchar(150) DEFAULT NULL COMMENT '고객 서비스센터 전화번호',
  `url` varchar(255) DEFAULT NULL COMMENT '고객 서비스센터 주소',
  `cs_email` varchar(255) DEFAULT NULL COMMENT '고객 서비스 담당 이메일',
  PRIMARY KEY (`project_cs_no`),
)

CREATE TABLE `project_platform` (
  `project_platform_no` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '조직 번호',
  `project_no` bigint(20) unsigned NOT NULL COMMENT '조직 생성자 계정 번호',
  `apk_url` json DEFAULT NULL COMMENT '국가별 apk 다운로드 url',
  `apk_release` json DEFAULT NULL COMMENT '국가별 apk 배포일자',
  `apk_version` json DEFAULT NULL COMMENT '국가별 apk 버전',
  `android` varchar(255) DEFAULT NULL,
  `android_deeplink` varchar(255) DEFAULT NULL,
  `ios` varchar(255) DEFAULT NULL,
  `ios_deeplink` varchar(255) DEFAULT NULL,
  `browser` varchar(255) DEFAULT NULL,
  `info_url` varchar(255) DEFAULT NULL,
  `install_guide` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`project_platform_no`),
)